[theme]

# Primary accent for interactive elements
primaryColor = '#908677'

# Background color for the main content area
backgroundColor = '#2A363B' 

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#1D2427'

# Color used for almost all text
textColor = '#8B959A'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"